[general]
connection = "Data Source=localhost\\SQLEXPRESS;Initial Catalog=AdventureWorksLT2019;Integrated Security=SSPI"
output = "AdventureWorks.fs"
namespace = "SampleApp.AdventureWorks"
cli_mutable = true
[readers]
reader_type = "Microsoft.Data.SqlClient.SqlDataReader"
